<?php
/* Русский языковый файл => <?php echo $Lang['logo'];?> */
$Lang = array(
	"logo"	=> "Геометрия",
	// decision/index.php
	"decision" => "Решение задачи",
	"decisions" => "Решение задач",
	"dated" => "Дата",
	"answer" => "Ответ",	
	"rating" => "Оценка",	
	// includes/footer.php
	"organization" => "КГУ Средняя Школа N11 отдела образования района Алтай © 2024, Все права защищены",
	"developer" => "Разработчик: Мамонтов Константин Евгеньевич",
	"attention" => "Уважаемый посетитель сайта! Данный сайт создан для защиты дипломного проекта",
	// includes/navigation.php
	"to_main" => "На главную",			
	"main" => "Главная",	
	"admin2"	=> "Администратор",	
	"considerations" => "Рассмотрение заявок",
	"contacts" => "Контакты",
	"decision"	=> "Решение задачи",	
	"decisions"	=> "Решения задач",	
	"entrance" => "Вход",
	"example" => "Пример задачи",
	"examples" => "Примеры задач",
	"lecture" => "Лекция",
	"lectures" => "Лекции",
	"logo_smal"	=> "Геометрия",
	"manager2"	=> "Менеджер",
	"personal_area" => "Личный кабинет",
	"my_decisions" => "Мои решения",
	"reports" => "Отчеты",
	"task" => "Задача",
	"tasks" => "Задачи",	
	"users" => "Пользователи",
	"visits" => "Посещения",	
	"welcome" => "Добро пожаловать",
	"exit" => "Выход",
	// language/index.php
	"language" => "Язык написания",
	"languages" => "Языки написания",
	// manual/index.php
	"manual" => "Учебный материал",
	"manuals" => "Дополнительно",
	"datem" => "Дата публикации",
	"manual_details" => "Краткое содержание",	
	"uploadname" => "Вложенный файл",				
	// news/index.php
	"daten" => "Дата новости",
	"details" => "Подробности",
	"news" => "Новость",
	"photo" => "Фотография",
	"title" => "Заголовок",
	"news_title" => "Заголовок новости",
	"news_details" => "Текст новости",	
	// news/list.php
	"search" => "Поиск",
	"reset" => "Сброс",
	// question/list.php
	"question" => "Вопрос к тестовому заданию",
	"questions" => "Вопросы к т.з",	
	"reply" => "Вариант ответа",	
	"reply1" => "Вариант ответа №1",	
	"ok1" => "Верный (да/нет)",	
	"reply2" => "Вариант ответа №2",	
	"ok2" => "Верный (да/нет)",	
	"reply3" => "Вариант ответа №3",	
	"ok3" => "Верный (да/нет)",	
	"reply4" => "Вариант ответа №4",	
	"ok4" => "Верный (да/нет)",	
	"reply5" => "Вариант ответа №5",	
	"ok5" => "Верный (да/нет)",	
	// report/index.php
	"visitor_date" => "Дата",
	"visitor_ip" => "IP-адрес",
	"visitor_login" => "Логин пользователя",
	"visitor_uri" => "Страница",
	"count" => "Количество",
	"protocol_test" => "Протокол тестирования",
	"protocol_task" => "Протокол решения задач",
	"datep" => "Дата",	
	"result" => "Результат, %",
	// task/index.php
	"section" => "Раздел",
	"topic" => "Тема задачи",
	"language" => "Язык выполнения работы",
	"problem" => "Задание",
	"solution" => "Решение",
	"id" => "Код",
	"your_answer_is_accepted" => "Ваш ответ принят",
	// test/index.php
	"test" => "Тестовое задание",
	"tests" => "Тестовые задания",
	"title_test" => "Название тестового задания",
	"run_test" => "Выполнение тестового задания",
	"run_tests" => "Выполнение тестовых заданий",
	"minute" => "Время для выполнения, мин.",
	"rate" => "Проходной бал, %",
	"testing_completed" => "Тестирование завершено",
	"passing_the_test_task" => "Прохождение тестового задания",
	// users/visits.php
	"datev" => "Дата и время",
	"visitor_ip" => "IP-адрес",
	"visitor_login" => "Логин",
	"visitor_uri" => "Страница",
	// users/index.php
	"admin" => "Администратор (да/нет)",
	"manager" => "Менеджер (да/нет)",
	"" => "",
	"" => "",
	// cabinet.php
	"user_login" => "Логин пользователя",
	"password" => "Пароль",
	"login" => "Имя пользователя",
	"email"	=> "Адрес электронной почты",
	"phone"	=> "Телефон",
	"enter"	=> "Введите",
	// contact.php
	"contact_information"	=> "Контактная информация",
	"address1" => "КГУ, средняя общеобразовательная школа N11, улица Брилина 31",
	"address2" => "г.Алтай, Алтайский район, Восточно-Казахстанская область, Казахстан",
	"phone_contact" => "+77075327722",
	"email_contact" => "zyrsc11@rambler.ru, приемная/бухгалтерия: 8(72335)6-33-80",
	"send_a_message" => "Отправить сообщение",
	"name" => "Имя пользователя",
	"details" => "Текст сообщения",
	"your_message_has_been_sent" => "Ваше собщение отправлено",
	// index.php
	"about_us"	=> "Назначение сайта",
	// links.php
	"links" => "Полезные ссылки",
	"links2" => "Ссылки для обучения математике",
	"textbook" => "Учебники",
	"video_lesson" => "Видеоуроки",
	// login.php
	"not_registered_yet" => "Еще не зарегистрированы",
	// register.php
	"registration" => "Регистрация",
	"you_already_have_an_account" => "У вас уже есть учетная запись",
	"login" => "Вход в систему",
	"phone" => "Телефон",	
	"all_fields_are_required" => "Все поля обязательны для заполнения!",
	"this_login_already_exists" => "Это имя пользователя уже существует! Попробуйте другое имя!",
	// Кнопки
	"back"	=> "Назад",
	"confirm_delete"	=> "Удалить запись",
	"confirm_start"	=> "Начать выполнение",
	"create"	=> "Создать",
	"edit"	=> "Изменить",
	"end"	=> "Завершить",
	"delete"	=> "Удалить",
	"read" => "Смотреть",
	"save" => "Сохранить",
	"select" => "Выбрать",
	"send" => "Отправить",
	"start" => "Начать",
	"up" => "Наверх",
	"update" => "Изменить",
	"accept" => "Принять",
	"select" => "Выберите...",
	// Общее
	"create_new" => "Создание",
	"read_record" => "Просмотр записи",
	"update_record" => "Измененить",
	"back" => "Назад",
	"page_up" => "Наверх",
	"solve" => "Решить",
	"yes" => "Да",
	"no" => "Нет",
	"delete_data"=> "Удалить данные",
	"date"=>"дата",
	"action"=> "действие"
);
?>